PPMDB/urls.py
from django.urls import path, include

urlpatterns = [
    path('deepb3p/', include('ppm.urls')),
]

ppm/urls.py
# -- coding: utf-8 --
# author : TangQiang
# time   : 2024/4/7
# email  : tangqiang.0701@gmail.com
# file   : urls.py

from django.urls import path
from . import views
app_name = 'ppm'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.HomeSearch.as_view(), name='search'),
    path('statistics/', views.statistics, name='statistics'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('document/', views.document, name='document'),
    path('browse/', views.BrowseView.as_view(), name='browse'),
    path('more/', views.showMore.as_view(), name='more'),
    #path('more/<type>/<id>', views.more, name='more'),
    path('disease/<str:sid>/', views.show_disease, name='show_disease'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="shortcut icon" href="{% static 'logo.png' %}">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>deepb3p</title> 
		<link rel="stylesheet" href="{% static 'dataTables/css/dataTables.bootstrap4.min.css' %}">
		<link rel="stylesheet" href="{% static 'base/css/style.css' %}">
		<link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'base/css/unicons.css' %}">
		<link rel="stylesheet" href="{% static 'base/css/fontawesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'base/css/solid.css' %}">
		<link rel="stylesheet" href="{% static 'base/css/load.css' %}">
		<link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
		{% block style %} 
		{% endblock %}
	</head>
	<body>
		<div class="antin-container">
			<header class="header-area overlay">
				<nav class="navbar navbar-expand-md navbar-dark">
					<div class="container">
						<a href="{% url 'ppm:home' %}" class="navbar-brand d-flex justify-content-center align-items-center">
							<img src="{% static 'logo.png' %}" width="45" height="45"
								class="d-inline-block justify-content-center align-items-center mr-2" alt="">
							<span class="">deepB3P</span>
						</a>
						<button type="button" class="navbar-toggler collapsed" data-toggle="collapse"
							data-target="#main-nav">
							<span class="menu-icon-bar"></span>
							<span class="menu-icon-bar"></span>
							<span class="menu-icon-bar"></span>
						</button>
						<div id="main-nav" class="collapse navbar-collapse">
							<ul class="navbar-nav ml-auto">
								<li>
									<a href="{% url 'ppm:home' %}" class="nav-item nav-link py-3" style="{{hoStyle}}">
										<i class="fas fa-home"></i> Home </a>
								</li>
                                <li class="dropdown">
                                    <a href="#" class="nav-item nav-link py-3" data-toggle="dropdown" style="{{seStyle}}">
                                        <i class="fas fa-search"></i>
                                            Search
                                    </a>
                                    <div class="dropdown-menu">
                                        <a href="{% url 'ppm:search' %}" class="dropdown-item">Predictor</a>
                                        <a href="{% url 'ppm:search' %}" class="dropdown-item">Generator</a>
                                    </div>
                                </li>
                                <li>
									<a href="{% url 'ppm:browse' %}" class="nav-item nav-link py-3" style="{{brStyle}}">
										<i class="fas fa-tasks"></i> Browse </a>
								</li>
								<li>
									<a href="{% url 'ppm:statistics' %}" class="nav-item nav-link py-3" style="{{stStyle}}">
										<i class="fas fa-chart-bar"></i> statistics </a>
								</li>
								<li>
									<a href="{% url 'ppm:document' %}" class="nav-item nav-link py-3" style="{{doStyle}}">
										<i class="fas fa-book"></i> Document </a>
								</li>
                                <li>
									<a href="{% url 'ppm:contact' %}" class="nav-item nav-link py-3" style="{{coStyle}}">
										<i class="fas fa-id-card"></i> Contact </a>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</header>
			{% block home %} 
			{% endblock %}
			<div class="antin-contain">
				<div class="container">
				{% block main %} 
				{% endblock %}
				</div>	
			</div>
			<div class="progress-wrap">
				<svg class="progress-circle svg-content" width="100%" height="100%" viewBox="-1 -1 102 102">
					x<path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
				</svg>
			</div>
			<!-- Site footer -->
			<footer class="site-footer">
				<div class="container" id="footer-container">
					<div class="row">
                        <div class="col-xs-4 col-md-4 d-flex flex-column">
							<div class="mt-auto text-left">
							    <h6 class="copyright-text"> Contact US</h6>
                                <p class="copyright-text"> E-mail: <font color="white">greatchen@cdutcm.edu.cn</font></p>
                                <p class="copyright-text">Copyright &copy; 2023 All Rights Reserved by <a href="https://chenweilab.cn/" target="_blank"style="color: #ffffff;">ChenWeiLab</a>. </p>
							</div>
						</div>
						<div class="col-xs-4 col-md-4 d-flex flex-column">
							<a target="_blank" href="https://www.revolvermaps.com/livestats/57ukqfgodk5/">
                                <img src="//rf.revolvermaps.com/h/m/a/0/ff0000/128/5/57ukqfgodk5.png" width="256" height="128" alt="Map" style="border:0;">
                            </a>
                        </div>
						<div class="col-xs-4 col-md-4 d-flex flex-column">
							<div class="mt-auto text-justify">
							    <h6 class="copyright-text"> Citation</h6>
                                <p class="copyright-text"> DeepB<sup>3</sup>P: A Transformer-Based Model for Identifying Blood-Brain Barrier Penetrating Peptides with Data Augmentation Using Feedback GAN</p>
							</div>
						</div>
					</div>
				</div>
			</footer>
		</div>
		<script src="{% static 'base/js/jquery.min.js' %}"></script>
		<script src="{% static 'base/js/style.js' %}"></script>
		<script src="{% static 'base/js/popper.min.js' %}"></script>
		<script src="{% static 'dataTables/js/jquery.dataTables.min.js' %}"></script>
		<script src="{% static 'dataTables/js/dataTables.bootstrap4.min.js' %}"></script>	
		<script src="{% static 'base/js/echarts.js' %}"></script>	
		{% block js %}
		{% endblock %}
	</body>
</html>

templates/compound.html
{% extends "./base.html" %} 
{% load static %}
{% block style %} 
<style>
table.dataTable thead th{
    background-color: #2e6da4;
        color: whitesmoke;
}
table.dataTable td>a{
    text-decoration:none;
	color:black;
}
table.dataTable tbody tr:hover {
  background-color: #eee;
}
</style>
{% endblock %} 
{% block main %} 
<nav aria-label="breadcrumb" class="mt-2">
	{% if type == 1%}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:home' %}">Home</a></li>
			<li class="breadcrumb-item active" aria-current="page">Browse</li>
		</ol>
	{% else %}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:search' %}">Search</a></li>
			<li class="breadcrumb-item active" aria-current="page">Compound</li>
		</ol>
	{% endif %}
</nav>
<div class="alert alert-success" role="alert">
	<i class="fas fa-align-justify"></i> | Total Compound: <span style="color: red">{{count.chembl}}
	</span>, Target Compound: <span style="color: red">{{ count.target }}</span>, Related Protein: <span style="color: red">{{ count.uniport }}</span>
</div>
<div class="mt-2" style="margin-bottom:25px">
	<table id="result" class="table table-bordered" style="table-layout:fixed;word-break:break-all;"></table>	
</div>
<div class="modal fade" id="loading-btn" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
	 aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content border-0" style="background: none;">
			<div class="modal-body text-center" style="background: none;">
				<div class="load">
					<hr/>
					<hr/>
					<hr/>
					<hr/>
				</div>
				<h2 style="color: white">Please Wait...</h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<script>
if (!String.prototype.format) {
	String.prototype.format = function () {
		var args = arguments;
		return this.replace(/{(\d+)}/g, function (match, number) {
			return typeof args[number] != 'undefined' ? args[number] : "";
		});
	};
};
$(document).ready(function() {
    $('#result').dataTable({
        "data": {{dataset|safe}},
		"deferLoading": 57,
		"autoWidth": true,
		"processing": true,
        "order": [[1, "desc"]],
        "columns": [
			{ "title": "chembl", "class": "features-td-left"},
			{ "title": "target","class": "features-td-left"},
			{ "title": "uniport","class": "features-td-left"},
			{ "title": "More","class": "features-td-center"},
        ],
		"columnDefs":[
			{
			    "render": function(data, type, row){
					if (row[0] != '-'){
						return '<a href="https://www.ebi.ac.uk/chembl/compound_report_card/{0}/" target="_blank">'.format(row[0])+row[0]+'</a>';
					}
					else{
						return row[0];
					}
			    },
			    "targets": 0
		    },
			{
			    "render": function(data, type, row){
					if (row[1] != '-'){
						return '<a href="https://www.ebi.ac.uk/chembl/compound_report_card/{0}/" target="_blank">'.format(row[1])+row[1]+'</a>';
					}
					else{
						return row[1];
					}
			    },
			    "targets": 1
		    },
		    {
			    "render": function(data, type, row){
				    return '<button class="btn btn-outline-secondary btn-sm" type="button" aria-label="Submit" value="Submit" onclick="submit1(\'{0}\')">View More </button>'.format(row[0]);
			    },
				"width": "8%",
			    "targets": 3
		    },
			
           {"targets": [3], "orderable": false}
	    ]
    });
} );
function submit1(uid) {
    var myForm = document.createElement("form");
    myForm.method = "GET";
    myForm.action = "{% url 'ppm:more' %}";
    var typeInput = document.createElement("input");
    typeInput.type = "hidden";
    typeInput.name = "type";
    typeInput.value = "compound";
    myForm.appendChild(typeInput);
    var uidInput = document.createElement("input");
    uidInput.name = "uid";
    uidInput.type = "hidden";
    uidInput.value = uid;
    myForm.appendChild(uidInput);
    document.body.appendChild(myForm);
    myForm.submit();
    $('#loading-btn').modal({
        backdrop: 'static',
        keyboard: false,
        show: true,
    });
    document.body.removeChild(myForm);
};
</script>
{% endblock %}

templates/disease.html
{% extends "./base.html" %} 
{% load static %}
{% block style %} 
<style>
table.dataTable thead th{
    background-color: #2e6da4;
        color: whitesmoke;
}
table.dataTable td>a{
    text-decoration:none;
	color:black;
}
table.dataTable tbody tr:hover {
  background-color: #eee;
}
</style>
{% endblock %} 
{% block main %} 
<nav aria-label="breadcrumb" class="mt-2">
	{% if type == 1%}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:home' %}">Home</a></li>
			<li class="breadcrumb-item active" aria-current="page">Browse</li>
		</ol>
	{% else %}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:search' %}">Search</a></li>
			<li class="breadcrumb-item active" aria-current="page">Disease</li>
		</ol>
	{% endif %}
</nav>
<div class="alert alert-success" role="alert">
	<i class="fas fa-align-justify"></i> | Total Disease: <span style="color: red">{{count.disease}}
	</span>, Tissue/Cell: <span style="color: red">{{ count.tiss }}</span>
</div>
<div class="mt-2" style="margin-bottom:25px">
	<table id="result" class="table table-bordered" style="table-layout:fixed;word-break:break-all;"></table>	
</div>
<div class="modal fade" id="loading-btn" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
	 aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content border-0" style="background: none;">
			<div class="modal-body text-center" style="background: none;">
				<div class="load">
					<hr/>
					<hr/>
					<hr/>
					<hr/>
				</div>
				<h2 style="color: white">Please Wait...</h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<script>
if (!String.prototype.format) {
	String.prototype.format = function () {
		var args = arguments;
		return this.replace(/{(\d+)}/g, function (match, number) {
			return typeof args[number] != 'undefined' ? args[number] : "";
		});
	};
};
$(document).ready(function() {
    $('#result').dataTable({
        "data": {{dataset|safe}},
		"deferLoading": 57,
		"autoWidth": true,
		"processing": true,
        "order": [[1, "desc"]],
		"responsive": true,
		"autoWidth": true,
        "columns": [
			{ "title": "Disease", "class": "features-td-left"},
			{ "title": "Tissue/Cell","class": "features-td-left"},
			{ "title": "DOID","class": "features-td-left"},
            { "title": "Uniport","class": "features-td-left"},
			{ "title": "More","class": "features-td-center"},
        ],
		"columnDefs":[
			{
			    "render": function(data, type, row){
					if (row[2] != '-'){
						return '<a href="https://disease-ontology.org/term/{0}/" target="_blank">'.format(row[2])+row[2]+'</a>';
					}
				    else{
						return row[2];
					}
			    },
                "targets": 2
		    },
            {
			    "render": function(data, type, row){
				    return '<a href="https://www.uniprot.org/uniprotkb/{0}/" target="_blank">'.format(row[3])+row[3]+'</a>';
			    },
				"width": "8%",
			    "targets": 3
		    },
		    {
			    "render": function(data, type, row){
				    return '<button class="btn btn-outline-secondary btn-sm" type="button" aria-label="Submit" value="Submit" onclick="submit1(\'{0}\')">View More </button>'.format(row[0]);
			    },
				"width": "8%",
			    "targets": 4
		    },
           {"targets": [4], "orderable": false}
	    ]
    });
} );
function submit1(uid) {
    var myForm = document.createElement("form");
    myForm.method = "GET";
    myForm.action = "{% url 'ppm:more' %}";
    var typeInput = document.createElement("input");
    typeInput.type = "hidden";
    typeInput.name = "type";
    typeInput.value = "disease";
    myForm.appendChild(typeInput);
    var uidInput = document.createElement("input");
    uidInput.name = "uid";
    uidInput.type = "hidden";
    uidInput.value = uid;
    myForm.appendChild(uidInput);
    document.body.appendChild(myForm);
    myForm.submit();
    $('#loading-btn').modal({
        backdrop: 'static',
        keyboard: false,
        show: true,
    });
    document.body.removeChild(myForm);
};
</script>
{% endblock %}

templates/enzyme.html
{% extends "./base.html" %} 
{% load static %}
{% block style %} 
<style>
table.dataTable thead th{
    background-color: #2e6da4;
        color: whitesmoke;
}
table.dataTable td>a{
    text-decoration:none;
	color:black;
}
table.dataTable tbody tr:hover {
  background-color: #eee;
}
</style>
{% endblock %} 
{% block main %} 
<nav aria-label="breadcrumb" class="mt-2">
	{% if type == 1%}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:home' %}">Home</a></li>
			<li class="breadcrumb-item active" aria-current="page">Browse</li>
		</ol>
	{% else %}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:search' %}">Search</a></li>
			<li class="breadcrumb-item active" aria-current="page">Enzyme</li>
		</ol>
	{% endif %}
</nav>
<div class="alert alert-success" role="alert">
	<i class="fas fa-align-justify"></i> | Total Enzymes: <span style="color: red">{{count.Ptase}}
	</span>, Organisms: <span style="color: red">{{ count.organism }}</span>, Proteins: <span style="color: red">{{ count.protein }}</span>
</div>
<div class="mt-2" style="margin-bottom:25px">
	<table id="result" class="table table-bordered" style="table-layout:fixed;word-break:break-all;"></table>	
</div>
<div class="modal fade" id="loading-btn" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
	 aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content border-0" style="background: none;">
			<div class="modal-body text-center" style="background: none;">
				<div class="load">
					<hr/>
					<hr/>
					<hr/>
					<hr/>
				</div>
				<h2 style="color: white">Please Wait...</h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<script>
if (!String.prototype.format) {
	String.prototype.format = function () {
		var args = arguments;
		return this.replace(/{(\d+)}/g, function (match, number) {
			return typeof args[number] != 'undefined' ? args[number] : "";
		});
	};
};
$(document).ready(function() {
    $('#result').dataTable({
        "data": {{dataset|safe}},
		"deferLoading": 57,
		"responsive": true,
		"autoWidth": true,
		"processing": true,
        "order": [[1, "desc"]],
		"responsive": true,
		"autoWidth": true,
        "columns": [
			{ "title": "Enzyme", "class": "features-td-left"},
			{ "title": "Organism","class": "features-td-left"},
            { "title": "Uniport","class": "features-td-left"},
			{ "title": "EID","class": "features-td-center"},
			{ "title": "More","class": "features-td-center"},
        ],
		"columnDefs":[
			{
				"width": "50%",
			    "targets": 1
		    },
            {
				"width": "20%",
			    "targets": 2
		    },
			{
				"visible": false,
			    "targets": 3
		    },
		    {
			    "render": function(data, type, row){
				    return '<a class="btn btn-outline-secondary btn-sm" type="button" aria-label="Submit" value="Submit" onclick="submit1(\'{0}\')">View More </a>'.format(row[3]);
				},
				"width": "8%",
			    "targets": 4
		    },
           {"targets": [4], "orderable": false},
	    ]
    });
} );
function submit1(uid) {
    var myForm = document.createElement("form");
    myForm.method = "GET";
    myForm.action = "{% url 'ppm:more' %}";
    <!-- var csrf = document.createElement("input"); -->
    <!-- csrf.type = "hidden"; -->
    <!-- csrf.name = "csrfmiddlewaretoken"; -->
    <!-- csrf.value = "{{ csrf_token }}"; -->
    <!-- myForm.appendChild(csrf); -->
    var typeInput = document.createElement("input");
    typeInput.type = "hidden";
    typeInput.name = "type";
    typeInput.value = "enzyme";
    myForm.appendChild(typeInput);
    var uidInput = document.createElement("input");
    uidInput.name = "uid";
    uidInput.type = "hidden";
    uidInput.value = uid;
    myForm.appendChild(uidInput);
    document.body.appendChild(myForm);
    myForm.submit();
    $('#loading-btn').modal({
        backdrop: 'static',
        keyboard: false,
        show: true,
    });
    document.body.removeChild(myForm);
};
</script>
{% endblock %}

templates/inhibitor.html
{% extends "./base.html" %} 
{% load static %}
{% block style %} 
<style>
table.dataTable thead th{
    background-color: #2e6da4;
        color: whitesmoke;
}
table.dataTable td>a{
    text-decoration:none;
	color:black;
}
table.dataTable tbody tr:hover {
  background-color: #eee;
}
</style>
{% endblock %} 
{% block main %} 
<nav aria-label="breadcrumb" class="mt-2">
	{% if type == 1%}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:home' %}">Home</a></li>
			<li class="breadcrumb-item active" aria-current="page">Browse</li>
		</ol>
	{% else %}
		<ol class="breadcrumb">
			<li class="breadcrumb-item align-items-center"><i class="fas fa-home"></i> <a href="{% url 'ppm:search' %}">Search</a></li>
			<li class="breadcrumb-item active" aria-current="page">Inhibitor</li>
		</ol>
	{% endif %}
</nav>
<div class="alert alert-success" role="alert">
	<i class="fas fa-align-justify"></i> | Total Enzymes: <span style="color: red">{{count.Ptase}}
	</span>, Organisms: <span style="color: red">{{ count.organism }}</span>, Proteins: <span style="color: red">{{ count.protein }}</span>
</div>
<div class="mt-2" style="margin-bottom:25px">
	<table id="result" class="table table-bordered" style="table-layout:fixed;word-break:break-all;"></table>	
</div>
<div class="modal fade" id="loading-btn" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
	 aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content border-0" style="background: none;">
			<div class="modal-body text-center" style="background: none;">
				<div class="load">
					<hr/>
					<hr/>
					<hr/>
					<hr/>
				</div>
				<h2 style="color: white">Please Wait...</h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<script>
if (!String.prototype.format) {
	String.prototype.format = function () {
		var args = arguments;
		return this.replace(/{(\d+)}/g, function (match, number) {
			return typeof args[number] != 'undefined' ? args[number] : "";
		});
	};
};
$(document).ready(function() {
    $('#result').dataTable({
        "data": {{dataset|safe}},
		"deferLoading": 57,
		"autoWidth": true,
		"processing": true,
        "order": [[2, "desc"]],
		"responsive": true,
		"autoWidth": true,
        "columns": [
			{ "title": "Inhibitor", "class": "features-td-left"},
			{ "title": "Enzyme","class": "features-td-left"},
			{ "title": "Enzyme Type","class": "features-td-left"},
            { "title": "Disease","class": "features-td-left"},
			{ "title": "DO id","class": "features-td-left"},
			{ "title": "More","class": "features-td-center"},
        ],
		"columnDefs":[
			{
				"render": function(data, type, row){
					if (row[3]!='-'){
						return '<a href="https://disease-ontology.org/term/{0}/" target="_blank">'.format(row[4])+row[3]+'</a>';
					}
					else{
						return row[3];
					} 
			    },
				"targets": 3
			},
		    {
			    "render": function(data, type, row){
				    return '<button class="btn btn-outline-secondary btn-sm" type="button" aria-label="Submit" value="Submit" onclick="submit1(\'{0}\')">View More </button>'.format(row[0]);
			    },
				"width": "8%",
			    "targets": 5
		    },
			{"targets": [4], "visible": false},
			{"targets": [5], "orderable": false}
	    ]
    });
} );
function submit1(uid) {
    var myForm = document.createElement("form");
    myForm.method = "GET";
    myForm.action = "{% url 'ppm:more' %}";
    var typeInput = document.createElement("input");
    typeInput.type = "hidden";
    typeInput.name = "type";
    typeInput.value = "inhibitor";
    myForm.appendChild(typeInput);
    var uidInput = document.createElement("input");
    uidInput.name = "uid";
    uidInput.type = "hidden";
    uidInput.value = uid;
    myForm.appendChild(uidInput);
    document.body.appendChild(myForm);
    myForm.submit();
    $('#loading-btn').modal({
        backdrop: 'static',
        keyboard: false,
        show: true,
    });
    document.body.removeChild(myForm);
};
</script>
{% endblock %}

templates/statistics.html
{% extends "./base.html" %} 
{% load static %}
{% block main %} 

<div class="mt-2" style="margin-bottom:25px">
	<div id="main" style="width: 600px;height:400px;"></div>
</div>
<div class="modal fade" id="loading-btn" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
	 aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content border-0" style="background: none;">
			<div class="modal-body text-center" style="background: none;">
				<div class="load">
					<hr/>
					<hr/>
					<hr/>
					<hr/>
				</div>
				<h2 style="color: white">Please Wait...</h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<script type="text/javascript">
      // 基于准备好的dom，初始化echarts实例
      var myChart = echarts.init(document.getElementById('main'));

      // 指定图表的配置项和数据
      var option = {
        title: {
          text: 'ECharts 入门示例'
        },
        tooltip: {},
        legend: {
          data: ['销量']
        },
        xAxis: {
          data: ['衬衫', '羊毛衫', '雪纺衫', '裤子', '高跟鞋', '袜子']
        },
        yAxis: {},
        series: [
          {
            name: '销量',
            type: 'bar',
            data: [5, 20, 36, 10, 10, 20]
          }
        ]
      };

      // 使用刚指定的配置项和数据显示图表。
      myChart.setOption(option);
    </script>	
{% endblock %}